### ISSUE TITLE
Client crash when logging in to server for the second time

### ISSUE THREAD

**Issue by mpolom** [mechaet/ModderationConfigs#22]
When i log into a server for the second time, my client crashes.

It logs in fine on a fresh install, and if I reinstall the client it logs in fine.

I am able to get all the way to the server loading screen before I encounter a crash.

Pastebin of the crash log is here: http://pastebin.com/Bdu0kUe0

**Comment by sandalle** [comment]
From the log:

```
Description: Ticking screen

java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Unknown Source)
        at mapwriter.Texture.getRGB(Texture.java:77)
        at mapwriter.BlockColourGen.getIconMapColour(BlockColourGen.java:31)
        at mapwriter.BlockColourGen.genBlockColours(BlockColourGen.java:145)
        at mapwriter.Mw.reloadBlockColours(Mw.java:398)
        at mapwriter.Mw.load(Mw.java:514)
        at mapwriter.Mw.onChunkLoad(Mw.java:647)
        at mapwriter.forge.EventHandler.eventChunkLoad(EventHandler.java:23)
```

So I've asked @pmmikes to remove MobiusCore-1.2.5_1.7.10.jar and Opis-1.2.5_1.7.10.jar from the mods directory to see if that helps. These have already been removed from the 1.1.3 server and should be removed in the 1.1.4 client (next release). Per [#11 crash-with-latest-version-of-kcauldron](https://bitbucket.org/ProfMobius/mobiuscore/issue/11/crash-with-latest-version-of-kcauldron#comment-None), the current version of MobiusCore is not compatible with the KCauldron that we use on the server, though most clients appear to function.

**Comment by mpolom** [comment]
Removing MobiusCore-1.2.5_1.7.10.jar and Opis-1.2.5_1.7.10.jar seems to have fixed the issue, and I was able to log in.

**Comment by sandalle** [comment]
MobiusCore-1.2.5_1.7.10.jar and Opis-1.2.5_1.7.10.jar are now removed via Solder for 1.1.4 update.
