### ISSUE TITLE
Modderation: Permabanned corruption

### ISSUE THREAD

**Issue by sandalle** [mechaet/ModderationConfigs#40]
This is for tracking the corruption of Modderation: Permabanned, which crashes with the following error

```
Description: Loading NBT data

java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at net.minecraft.nbt.NBTTagCompound.func_152447_a(NBTTagCompound.java:383)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:48)
        at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
        at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
        at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
        at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
        at net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216)
        at net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200)
        at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:421)
        at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at net.minecraft.nbt.NBTTagCompound.func_152447_a(NBTTagCompound.java:383)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:48)
        at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)

-- NBT Tag --
Details:
        Tag name: Tickets
        Tag type: 9
Stacktrace:
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
        at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
        at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
        at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
        at net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216)
        at net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200)
        at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:421)
        at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
        at java.lang.Thread.run(Thread.java:745)
```

The server backup that I had contained the following invalid YAML files (**data** instead of **ASCII text** or **empty**) and make Bukkit crash on Null-Exception at start:
- commands.yml: data
- bukkit.yml: data
- kcauldron.yml: data
- tileentities.yml: data
- cauldron.yml: data

**Comment by sandalle** [comment]
Using the following command, I found that **world/forcedchunks.dat** is the last file opened which has the "Tickets" Tag. Removing this file allows the server to start~~, but anytime I join I am immediately kicked. Still working on verifying that removing world/forcedchunks.dat fixes the world and allows players to log in and interact.~~

Trace opened files for _start.sh_ and all forks:
`$ strace -t -e trace=open,close,read,getdents,write,connect,accept -ff -o strace ./start.sh`

start.sh consists of:

```
#!/bin/bash

[[ -x /etc/profile.d/java.sh ]] && source /etc/profile.d/java.sh

        JAVA="$(which java)"
         JAR='KCauldron.jar'
START_MEMORY=1024
  MAX_MEMORY=4096

"${JAVA}" -Xmx${MAX_MEMORY}M -Xms${START_MEMORY}M -Xmn1G -Xss4M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+UseLargePages -Djava.net.preferIPv4Stack=true -Djline.terminal=jline.UnsupportedTerminal -Djava.util.prefs.userRoot={SERVER_DIR} -jar "${JAR}" nogui
```

For the client disconnect, I was still using Forge 1.7.10-Forge10.13.4.1566-1.7.10 instead of 1.7.10-Forge10.13.4.1448-1.7.10 on the client from testing Modderation 1.1.6. :/

**Comment by sandalle** [comment]
Overworld (including Magnus' EMC Farm/Mekanism Reactor, Joint Town, Spawn, and mechaet's towers), The Village (DIM10), and Goon Labs (DIM16) appear to all work after removing **world/forcedchunks.dat** and fixing the above mentioned YAML (.yml) files. The only downsides which I've found are:
- All Ender IO Dimensional Transceivers have lost their frequencies and all configured frequencies have disappeared.
  - Possibly a missing or corrupt world/enderio/dimensionalTransceiver.json .
- Command-button at Spawn to move a player to mining world does nothing.
  - The RFTools Dialing Device also says that the "Mining World" is now an "Invalid destination".
  - `[21:33:29] [Server thread/WARN]: Cannot Hotload Dim: Could not get provider type for dimension 63, does not exist`

**Comment by sandalle** [comment]
Server is online and appears to be functioning now. :)
