### ISSUE TITLE
Factorization 0.8.88.8.8888* is broken with Cauldron

### ISSUE THREAD

**Issue by sandalle** [mechaet/ModderationConfigs#8]
[14:26:50 WARN]: net.minecraft.world.MinecraftException: The save folder for world ./world/DIM-7 is being accessed from another location, aborting
[14:26:50 WARN]:        at net.minecraft.world.storage.SaveHandler.func_75762_c(SaveHandler.java:98)
[14:26:50 WARN]:        at net.minecraft.world.World.func_72906_B(World.java:4238)
[14:26:50 WARN]:        at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1080)
[14:26:50 WARN]:        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1046)
[14:26:50 WARN]:        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519)
[14:26:50 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
[14:26:50 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[14:26:50 WARN]:        at java.lang.Thread.run(Thread.java:745)

From [MCF Factorization Thread Comment #2677](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284592-factorization-0-8-88-8-8888-the-update-that-ate?comment=2677).

```
Cauldron Setup:

        Server Version: cauldron-1.7.10-1.1286.06.216-server.jar
        Forge Mod Loader version: 7.10.85.1286 for Minecraft 1.7.10
            Soft crashes with dimension duplicate error, causes any save-all function to error, regardless if your using a free dimension or not.

        Server Version: cauldron-1.7.10-1.1307.06.218-server.jar
        Forge Mod Loader version: 7.10.88.1307 for Minecraft 1.7.10
            Soft crashes with dimension duplicate error, causes any save-all function to error, regardless if your using a free dimension or not.


Forge Setup:

        Server Version: forge-1.7.10-10.13.2.1286-universal.jar

        Forge Mod Loader version: 7.10.85.1291 for Minecraft 1.7.10
            Working with no dimension issues.

        Server Version: forge-1.7.10-10.13.2.1291-universal.jar
        Forge Mod Loader version: 7.10.85.1286 for Minecraft 1.7.10
            Working with no dimension issues.
```

In [MCF Factorization Thread Comment #2689](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284592-factorization-0-8-88-8-8888-the-update-that-ate?comment=2689), the mod author basically says Cauldron is a lost cause:

```
I'm afraid cauldronbukkitspigot's a lost cause; you'll have to use a pre-8's version of FZ.
```

The fix is to go to a version of Factorization before "8's", which I'm unsure if he means before 0.8.88.8.8888 (so [0.8.88.7](http://download758.mediafire.com/77bj8gwok1bg/c7614ip3borr17o/Factorization-1.7.10-0.8.88.7.jar), which is the only other posted release he has), or some 0.7.x that does not exist even all the way back to Minecraft 1.6.4. So I'm thinking 0.8.88.7 is what he means.

A note from the [MCF Factorization Thread Original Post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284592-factorization-0-8-88-8-8888-the-update-that-ate):
# Hammer

> Hammer (or FZDS, for FactoriZation Dimensional Slices) is a WIP engine upgrade for Minecraft that gives it the ability to move and rotate chunks arbitrarily. It is used to implement the Colossi and the Twisting Block, with more things to come. Unfortunately there are some bugs that happen with Optifine & bukkit/spigot/cauldron right now, and I'm not really able to fix them. However there will also be bugs with other mods, so please let me know about them.

0.8.88.7 does not have the Hammer dimension (DIM-7), and also does not have Colossi, among [other changes](https://dl.dropboxusercontent.com/u/76265666/changelogs/Changelog-1.7.10-0.8.88.8.8888h.txt).

**Comment by sandalle** [comment]
Mod author has disabled Hammer (FZDS) automatically for servers with Cauldron instead of fixing this issue in 0.8.92.
